### ISSUE TITLE
[Request]: add button in UI for creating new task

### ISSUE THREAD

**Issue by mrazarny** [dromse/obsidian-grind-manager#35]
### What kind of feature do you want?

Add the ability to remove non recurring done tasks to the history folder instead of leaving them in their place if its possible  
+ 
if u can add a button to create tasks and specify where you want to be i.e  + button : 

whats the name of the task? 
recurring?
diff?
path?

### Additional questions

- [ ] I want to work on this feature request

**Comment by dromse** [comment]
Hello, @mrazarny. Thank you for your suggestion.
It's a pity but I'm not planning to implement a feature for moving tasks inside the vault at the moment. 
However, if someone suggests a pull request for it, I'll be happy to consider it. As for your second request, yes, I'll definitely add a button for creating new tasks. This feature will be included in either version 1.3 or 1.4.

**Comment by mrazarny** [comment]
Ty buddy 

btw your plugin literally is the exact same way as i wanted it to be its almost perfect for my use case so (Ty)

btw another idea 😅 
i actually was scrolling in the plugin shop when i saw it and was just like how is this only 715 downloads 

so i would recommend to either change the plugin name to make it more popular in search or the description

i.e
from : "task management with rewards system"

to: "Gamify your task/todo management with rewards system"

**Comment by dromse** [comment]
Hey @mrazarny, my plugin is quite new—I only uploaded it a month ago. So far, it hasn't been mentioned on popular platforms like YouTube etc. The only reference I've found is in this article about new Obsidian plugins [New Obsidian Plugins](https://beingpax.medium.com/new-obsidian-plugins-ink-slides-extended-gamified-tasks-daily-prompt-more-ae85207d1d86), which briefly talks about it. 

Thanks for a new description, I'm considering updating the description on your suggestion. However, I recall that updating descriptions in the Obsidian community plugins requires contacting moderation, which can take a long time 😅

**Comment by mrazarny** [comment]
Grind manager is good but the other one is better ya also i faced a problem basically i have some doing task and todo tasks but i can only filter either to do + doing so i think if u can add that to filters todo+doing ill appreciate it totally 

+ for the name your suggestion is good i don't have ideas right now as i was foing math exams so im burn out right now so if u wanna to chat about features or anything massage me on reddit "MRAZARNY"

**Comment by mrazarny** [comment]
Grind manager is good but the other one is better ya also i faced a problem basically i have some doing task and todo tasks but i can only filter either to do + doing so i think if u can add that to filters todo+doing ill appreciate it totally 

+ for the name your suggestion is good i don't have ideas right now as i was foing math exams so im burn out right now so if u wanna to chat about features or anything massage me on reddit "MRAZARNY"

btw i faced another thing that I wanna you to change (i m just trying to help)


every/day tag starts counting since yhe the last time i did the habit

for example if i have every day gem habit and ine day i went to the gem at 11pm and marked as done 

the task wont appear till 11 pm next day which is frustrating just make it that it resets with day time reset like when 12pm hits all every day recurring resets

**Comment by dromse** [comment]
@mrazarny, maybe this is a bug, the real implementation of this feature must show tasks on new date and neglect specific time (I didn't do nothing with it in realization), maybe something went wrong with your locale time and plugin count your next day, does all tasks not resets after 12 pm?
