### ISSUE TITLE
[Bug]: Reading Properties as items in Rewards/History pool

### ISSUE THREAD

**Issue by Ackasi** [dromse/obsidian-grind-manager#43]
### What happened?

My properties, which regenerate due to syncing complications and such, are read by the Grind Manager reward menu as individual items for rewards, and I am unable to remove them

### Steps to reproduce

create the rewards/history doc, have file properties, shows in menu.

### Plugin Version

Recent

### Obsidian Version

Recent

### What platform are you seeing the problem on? (Can be multiple)

Windows

### Relevant log output

```shell
N/A
```

### Additional questions

- [ ] I want to work on this issue

**Comment by dromse** [comment]
Hi, @Ackasi, for history file you can change format to .txt or other which removes file from obsidian indexing I think it can help somehow. Later I will add feature for ignore frontmatter in rewards file. 

Thanks for a bug report!

**Comment by dromse** [comment]
@Ackasi, does changing the history file format help? I'm about to start working on this bug report. To clarify, will it be sufficient to add a feature that ignores the frontmatter in the rewards file?

**Comment by Ackasi** [comment]
it didn't seem to make much of a difference, i think the feature would be
necessary

**Comment by dromse** [comment]
@Ackasi, update to new version, I fixed it in 1.2.3.
