### ISSUE TITLE
Feature request : add a setting to filter the tasks from a note

### ISSUE THREAD

**Issue by MelodyDuplaix** [dromse/obsidian-grind-manager#6]
For the moment, we can only filter with the status of the task. This can be a problem, especially if you have a lot of tasks and don't want all of them to yield rewards.
Would it be possible to add an option where we would put a path to a note, to only retrieve the tasks on this note?
If not, will there be more advanced ways to filter tasks in the future?
Thanks in advance,

**Comment by rchaklashiya** [comment]
I would also like to second this feature request.
Currently I have way too many checkboxes in my vault and filter out the important ones that are actual tasks with #task using the tasks plugin.
I think having the ability to filter by hashtag would be essential for me to move forward with using this plugin.
It's an awesome plugin and I really want to use it but for me I think this would be necessary to move forward

**Comment by dromse** [comment]
@rchaklashiya Hi! Thanks for your suggestion, I think to add filter by hashtag in version 1.1.0 on 1 May or early. 
Currently I focus my work on fixing bugs till middle of this month. After I will implement more features.

**Comment by dromse** [comment]
I added this feature d1f890dae8e5b91703570b2ebea9fc6e27024c85 it will be available from 1.1.0 (Release 15 April 2024). So I close this issue. Thanks for suggestion!
