### ISSUE TITLE
[Feature Request] Ignore files and folders

### ISSUE THREAD

**Issue by eduongAZ** [dromse/obsidian-grind-manager#7]
Feature: In the setting, specify files and folders to ignore parsing todos

Usecase: I have templates with todos that are being parsed by the grind manager. I would like the grind manager to skip these todos in templates.

**Comment by dromse** [comment]
Hi, @eduongAZ! Thanks for a suggestion. I'll try to implement it in the near future.

**Comment by dromse** [comment]
I added this feature in ab77c95b35bbaae82da4169fea14cb9a5cea646d, it will be available in 1.1.0 (Release 15 April)
